engine = create_engine('postgresql:///arXivdata')
cnx = engine.raw_connection() 
train = pd.read_sql("SELECT * FROM arxivsmall WHERE groupnum <> 1", cnx)
test = pd.read_sql("SELECT * FROM arxivsmall WHERE groupnum =1", cnx)
cnx.close() 
